name: Deploy to AWS using Terraform

on:
  push:
    branches: [ test ]

jobs:
  terraform:
    name: Terraform AWS Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Export creds
      run: |
            echo "ARM_CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
            echo "ARM_CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
            echo "ARM_SUBSCRIPTION_ID=${{ secrets.SUB_ID }}" >> $GITHUB_ENV
            echo "ARM_TENANT_ID=${{ secrets.TEN_ID }}" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform init
      working-directory: "./Terraform"

    - name: Terraform Plan
      run: terraform plan
      working-directory: "./Terraform"

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: "./Terraform"

    